#!/bin/bash

#SBATCH -p gpu # partition (queue)
#SBATCH -N 1   # number of nodes
#SBATCH --mem 12G # memory pool for all cores
#SBATCH -n 2 # number of cores
#SBATCH -t 0-01:00 # time (D-HH:MM)
#SBATCH --gres gpu:1 # request 1 GPU (of any kind)
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ucqfnsi@ucl.ac.uk

# Load the SLEAP module
module load SLEAP

# Go to the training job directory
cd /ceph/scratch/neuroinformatics-dropoff/SLEAP_HPC_test_data/labels.v001.slp.inference_job

# Run the inference script generated by SLEAP
bash inference-script.sh
