#!/bin/bash

#SBATCH -J slp_train1 # job name
#SBATCH -p gpu # partition (queue)
#SBATCH -N 1   # number of nodes
#SBATCH --mem 12G # memory pool for all cores
#SBATCH -n 2 # number of cores
#SBATCH -t 0-04:00 # time (D-HH:MM)
#SBATCH --gres gpu:1 # request 1 GPU (of any kind)
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ucqfnsi@ucl.ac.uk

# Load the SLEAP module
module load SLEAP

# Define directories for data and exported training job
DATA_DIR="/ceph/scratch/sirmpilatzen/PoseEstimation/Mouse-EPM/derivatives/SLEAP"
SLP_JOB_NAME="labels.v001.slp.training_job"
SLP_JOB_DIR=$DATA_DIR/$SLP_JOB_NAME

# Go to the job directory
cd $SLP_JOB_DIR

# Run the training script generated by SLEAP
./train-script.sh
